### PR TITLE
Fix plot sorting

### LINKED ISSUE #172: sort() not working on R v 4.0.3
Thanks to Mannie Lopez (USGS) for pointing out that sort() appears to have no effect anymore
I thought it was because base R now seems to take over when functions are conflicted, but when `burnr::sort()` or `burnr::sort.fhx()` are specified, an error is triggered
```{r}
Error: 'sort' is not an exported object from 'namespace:burnr'
# and
Error: 'sort.fhx' is not an exported object from 'namespace:burnr'
```

Also, using `burnr:::sort.fhx()` resulted in no error, there was also no affect.

### PR DESCRIPTION
**Pull request by chguiterman**
Fix to internal function used by `plot_demograph()` to correct sorting results in the plot.

Close #172 .

### CODE REVIEW

**Comment by brews** [comment]
This is giving you a red flag on CI/CD because it was requiring a status response from `travis` I just removed that so CI/CD status checks should now work properly with PRs. Sorry about that.

**Comment by brews** [comment]
This PR isn't marked as a "draft" so I assume this is ready to merge, @chguiterman ?

**Comment by chguiterman** [comment]
> This PR isn't marked as a "draft" so I assume this is ready to review/merge, @chguiterman ?

Yes, it's ready @brews

**Review by brews — APPROVED** [review]
LGTM. Thanks for the fix!

**Pull request merged**
