### PR TITLE
Merge updates in stats.R

### PR DESCRIPTION
**Pull request by chguiterman**
Includes: new function `percent_scarred()`, update to `sample_depth()` and added output in `sea` list object

### CODE REVIEW

**Comment by brews** [comment]
Looks like travis is failing you because of [line 279, 281, 284](https://github.com/chguiterman/burnr/blob/43e780d332076c4cb7371360f4bbb1aa61f9c6d7/R/stats.R#L279-L284).

Try to change `count` to `plyr::count` on these lines...

**Comment by chguiterman** [comment]
I think I got it. Using ddply was not the right approach. Changed that to
plyr::count and the unit tests cleared under devtools::check()

--
Christopher Guiterman, Ph.D.
Research Associate
Laboratory of Tree-Ring Research
University of Arizona

**Comment by brews** [comment]
Nice work @chguiterman! Thanks for the code. The merge is complete and things look good from my end!

**Comment by chguiterman** [comment]
Good deal. Thanks

**Pull request merged**
