### PR TITLE
Seasonality and plotting updates

### PR DESCRIPTION
**Pull request by chguiterman**
Updates to `burnr` include:

* Update `count_event_position()` to accommodate newly added (and future) positions in rec_ype
* Bug fix in `plot_demograph()` to handle discontinuous recording periods. #78
  * Bug fix required a new function (`get_rec_tbl()`) to generate table of recording segments. Not exported.
* Added spring dormant to set of rec_types. Another "noncanon" descriptor for fire scar seasonality. This aids in canonizing "D" dormant scars as the unknown year of a dormant scar (in the Northern Hemisphere) 
* [Internal] Update README to Rmarkdown (.Rmd) file with `usethis::use_readme_rmd()`
* Fix typo in citation file

### CODE REVIEW

**Comment by brews** [comment]
Thanks for the code @chguiterman!

Added WIP to title as it sounds like more progress might be coming...

**Comment by brews** [comment]
Noticed that our MacOS CI build has failed. That might be an internal issue with Travis CI rather than the PR. These MacOS runs have always been trouble. I'll retry it.

**Comment by chguiterman** [comment]
I've had a bunch of build fails for MacOS lately. I'm not sure what's going
on, but it seems to be linked to Travis and/or other libraries. It should
resolve itself, but this one looks like a timeout. Is it possible to
increase the build period?
--
Christopher Guiterman, Ph.D.
Research Associate
Laboratory of Tree-Ring Research
University of Arizona

**Comment by chguiterman** [comment]
FYI @brews, Travis Tests passed on chguiterman/burnr@master this morning. Try re-running the pull request again when you can.

**Comment by brews** [comment]
@chguiterman, did you make a change to the code or is it that CI is simply working?

**Comment by chguiterman** [comment]
@brews Seems like CI is now working. The MacOS build took 4 minutes today, and it timed out yesterday at >11 minutes. No new code

**Comment by chguiterman** [comment]
@brews, can we re-run Travis? I don't have privileges to hit go.

**Comment by brews** [comment]
@chguiterman I was also thinking that it was a permissions issue and that maybe **you** could restart the build. I also do not have the option to restart the build. Ug.

**Comment by brews** [comment]
@chguiterman Would you please try to push an empty commit (following https://travis-ci.community/t/restart-a-build-check-in-a-pr-that-failed-due-to-a-network-issue/4689)?

So this is running `git commit --allow-empty` and then pushing onto your working branch.

Thanks!

**Comment by chguiterman** [comment]
Thanks @brews! Looks like that worked to trigger a new build. Let's see how it ends up...

**Comment by chguiterman** [comment]
So the Travis build is passing, although it suggests some changes. I can do those. I think the PR is failing because the coverage dropped below 80%. That sounds right @brews? I'll work to add some unit tests and get the coverage up.

**Comment by brews** [comment]
Excellent, thanks much @chguiterman!

I believe that coveralls is failing you because you are decreasing our coverage. I'm willing to wave this as long as it's not a huge change in test coverage, and you test any new features. I didn't set a failure threshold for the project's coverage.

**Comment by chguiterman** [comment]
@brews please wave it for now. The package is fully operational. I'll add more tests and submit another PR sometime soon. There are other things on my list to add to `burnr`, but I'd like these changes in the master branch now for an upcoming paper submission. Thanks!

**Comment by brews** [comment]
@chguiterman, are you suggesting adding more before doing a CRAN release or are you fine just with this sitting in `master`?

For the future, I feel like this is a pretty big PR. It might be easier if we break our PRs down to focus on individual fixes and new features - if possible.

**Comment by chguiterman** [comment]
@brews, No need for a CRAN release until we've fixed up a few things, most importantly the unit tests. I'm fine with these changes staying in `master` for now. 

Good to know about the size of the PR. I can submit smaller PRs. This got backlogged from last summer, and there were some issues with my fork falling behind ltrr-master but also having committed changes. Hence the large number of commits to get that squared away.

**Comment by brews** [comment]
👍  Cool. To be explicit, @chguiterman, are you ready for this to merge now or do you want more changes in this PR?

**Comment by chguiterman** [comment]
merge it!

**Comment by brews** [comment]
Resolving WIP and merging...

**Pull request merged**
