### PR TITLE
Bug fix in vignettes

### LINKED ISSUE #179: CRAN submission for package burnr_0.6.0.tar.gz does not pass the incoming checks automatically
CRAN is bouncing our package release because of an issue with one of the vignettes. This vignette passed local and CI/CD check but is failing on the CRAN win_devel check.

Specifically, it looks like the issue is with the `facet_comps.Rmd` vignette pulling in remote data from from the NOAA server.
```
* checking re-building of vignette outputs ... [8s] WARNING
Error(s) in re-building vignettes:
--- re-building 'facet_comps.Rmd' using rmarkdown
Quitting from lines 24-31 (facet_comps.Rmd) 
Error: processing vignette 'facet_comps.Rmd' failed with diagnostics:
cannot open the connection
--- failed re-building 'facet_comps.Rmd'

--- re-building 'introduction.Rmd' using rmarkdown
--- finished re-building 'introduction.Rmd'

SUMMARY: processing the following file failed:
  'facet_comps.Rmd'

Error: Vignette re-building failed.
Execution halted
```

You can check/replicate this by running `devtools::check_win_devel()` from the root of the package directory. It replicates the error.

Full output from the automated check is:
```
* using log directory 'd:/RCompile/CRANincoming/R-devel/burnr.Rcheck'
* using R Under development (unstable) (2021-02-20 r80030)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'burnr/DESCRIPTION' ... OK
* this is package 'burnr' version '0.6.0'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... Note_to_CRAN_maintainers
Maintainer: 'Steven Malevich <sbmalev@gmail.com>'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking serialization versions ... OK
* checking whether package 'burnr' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [8s] OK
* checking Rd files ... [1s] OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking R/sysdata.rda ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... [7s] OK
** running examples for arch 'x64' ... [8s] OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
** running tests for arch 'i386' ... [9s] OK
  Running 'testthat.R' [8s]
** running tests for arch 'x64' ... [10s] OK
  Running 'testthat.R' [9s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... [8s] WARNING
Error(s) in re-building vignettes:
--- re-building 'facet_comps.Rmd' using rmarkdown
Quitting from lines 24-31 (facet_comps.Rmd) 
Error: processing vignette 'facet_comps.Rmd' failed with diagnostics:
cannot open the connection
--- failed re-building 'facet_comps.Rmd'

--- re-building 'introduction.Rmd' using rmarkdown
--- finished re-building 'introduction.Rmd'

SUMMARY: processing the following file failed:
  'facet_comps.Rmd'

Error: Vignette re-building failed.
Execution halted

* checking PDF version of manual ... OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 1 WARNING
```

### PR DESCRIPTION
**Pull request by chguiterman**
Close #179.

### CODE REVIEW

**Comment by chguiterman** [comment]
R-CMD-check failed bc R4.0.4 failed to build on the ubuntu remote. Trying again

**Comment by brews** [comment]
Thanks for this @chguiterman !

I updated the PR to reference the original issue. Have you checked this against `devtools::check_win_devel()`, @chguiterman ?

**Comment by chguiterman** [comment]
@brews Just ran `devtools::check_win_devel()` -- you should be getting the results shortly via email

Did you set that up? Cool.

**Comment by brews** [comment]
Looks like this passed checks!

I'll double check this and attempt a new resubmission this weekend.

Thanks for your help, @chguiterman!

**Review by brews — APPROVED** [review]
By all indications, this appears to solve the vignettes issue.

Thanks for the help with this!

**Comment by chguiterman** [comment]
Great! Thanks @brews

**Pull request merged**
