### PR TITLE
Update run_sea and sort.fhx

### PR DESCRIPTION
**Pull request by chguiterman**

### CODE REVIEW

**Comment by brews** [comment]
This merge looks like it deals with #58 . I'm going to try to get to this today.

**Comment by brews** [comment]
I've merged these changes in with a new 'seas' branch. I'll update this so that it passes R checks and such. When you file your pull requests, merge all of your seas code in with the 'seas' branch, not the master branch.

Assuming that all goes well, are you fine with this code, so far, going out in a patch?  If so, I'll merge this with master.

**Comment by chguiterman** [comment]
Thanks. I'm good with this going to a patch.

**Comment by brews** [comment]
Okay. I merged these changes with master.

**Comment by chguiterman** [comment]
Good deal. Thanks.

**Pull request closed without merging**
